FROM php:7.4-fpm

ARG WWWGROUP

RUN apt-get update \
    && apt-get -y --no-install-recommends install \
    mcrypt \
    libxml2-dev \
    openssl \
    git \
    nano \
    curl \
    libpng-dev \
    libonig-dev \
    libxml2-dev \
    zip \
    unzip \
    supervisor \
    && apt-get -y install \
        wget \
        gosu \
    && apt-get autoremove --purge -y && apt-get clean \
    && rm -rf /var/lib/apt/lists/* /tmp/* /var/tmp/* \
    && apt-get update

RUN docker-php-ext-install -j$(nproc) \
    opcache \
    intl \
    pdo_mysql \
    mbstring \
    exif \
    pcntl \
    bcmath \
    gd

RUN pecl install apcu-5.1.20 && docker-php-ext-enable apcu

COPY php.ini $PHP_INI_DIR/conf.d/

# Get latest Composer
COPY --from=composer:latest /usr/bin/composer /usr/bin/composer

# Create system user to run Composer and Artisan Commands
RUN groupadd --force -g $WWWGROUP sail
RUN useradd -ms /bin/bash --no-user-group -g $WWWGROUP -u 1000 sail

COPY start-container /usr/local/bin/start-container
COPY supervisord.conf /etc/supervisor/conf.d/supervisord.conf
RUN chmod +x /usr/local/bin/start-container

# Set working directory
WORKDIR /var/www/

# USER sail

# Expose port 9000 and start php-fpm server
EXPOSE 9000

CMD ["php-fpm"]
